name: Sync Leetcode
on:
  workflow_dispatch:     
  schedule:
    - cron: "0 */5 * * *"  

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4 

      - name: Sync
        uses: jasonma0011/leetcode-sync@v2.0.0  
        with:
          github-token: ${{ github.token }}
          leetcode-csrf-token: ${{ secrets.LEETCODE_CSRF_TOKEN }}
          leetcode-session: ${{ secrets.LEETCODE_SESSION }}
          destination-folder: solutions
